openapi: "3.0.0"
info:
  version: 1.0.0
  title: MBTI channel API docs
  description: MBTI channel의 API 문서입니다
  license:
    name: MIT

servers:
  - url: http://localhost:8001/

tags:
  - name: "auth"
    description: auth

paths:
  # auth
  /auth/login:
    $ref: "./paths/auth/login.yaml"
  /auth/me:
    $ref: "./paths/auth/me.yaml"
  /auth:
    $ref: "./paths/auth/index.yaml"
  /auth/logout:
    $ref: "./paths/auth/logout.yaml"
