openapi: "3.0.0"
info:
  version: 1.0.0
  title: MBTI channel API docs
  description: MBTI channel의 API 문서입니다
  license:
    name: MIT

servers:
  - url: http://localhost:8001/

tags:
  - name: "users"
    description: 유저
  - name: "posts"
    description: 게시글
  - name: "comments"
    description: 댓글 | 대댓글
  - name: "notifications"
    description: 알림
  - name: "bookmarks"
    description: 북마크

paths:
  # users
  /users/login:
    $ref: "./paths/users/login.yaml"
  /users/check:
    $ref: "./paths/users/check.yaml"
  /users/me:
    $ref: "./paths/users/me.yaml"
  /users/me/nickname:
    $ref: "./paths/users/me.nickname.yaml"
  /users/accessToken:
    $ref: "./paths/users/access-token.yaml"
  /users/logout:
    $ref: "./paths/users/logout.yaml"
  /users:
    $ref: "./paths/users/index.yaml"
  /users/posts:
    $ref: "./paths/users/posts.yaml"
  /users/comments:
    $ref: "./paths/users/comments.yaml"

  # posts
  /posts:
    $ref: "./paths/posts/index.yaml"
  /posts/trending:
    $ref: "./paths/posts/trending.yaml"
  /posts/search:
    $ref: "./paths/posts/search.yaml"
  /posts/{id}:
    parameters:
      - in: path
        name: id
        type: integer
        description: 상세히 보고 싶은 게시글 아이디
    $ref: "./paths/posts/id.yaml"

  # comments
  /comments:
    $ref: "./paths/comments/index.yaml"
  /comments/{id}:
    $ref: "./paths/comments/id.yaml"
  /comments/replies:
    $ref: "./paths/comments/replies.yaml"

  # notification
  /notifications:
    $ref: "./paths/notifications/index.yaml"
  /notifications/all/readAt:
    $ref: "./paths/notifications/all.yaml"
  /notifications/{id}/readAt:
    parameters:
      - in: path
        name: id
        type: integer
        description: Notification ID
    $ref: "./paths/notifications/id.yaml"

  # bookmark
  /bookmarks:
    $ref: "./paths/bookmarks/index.yaml"
  /bookmarks/{id}:
    parameters:
      - in: path
        name: id
        type: integer
        description: Post ID
    $ref: "./paths/bookmarks/id.yaml"

  # report
  /reports:
    $ref: "./paths/reports/index.yaml"

# #1) Define the security scheme type (HTTP bearer)
components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes
    cookieAuth: # arbitrary name for the security scheme; will be used in the "security" key later
      type: apiKey
      in: cookie
      name: JSESSIONID # cookie name

