name: Build and Push Dev Docker Image
on:
  #test
  pull_request:
    branches: ["main"]
  #test
  push:
    branches:
      - main
jobs:
  build-and-push-dev-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create development env file
        run: |
          touch .development.env
          echo PORT=${{ secrets.PORT }} >> .development.env
          cat .development.env

        # 이 작업은 buildx를 사용하는 경우 워크플로의 다음 단계에서 사용할 수 있는 빌더를 만들고 부팅합니다.
        # 기본적으로 도커 컨테이너 빌더 드라이버는 BuildKit 컨테이너 덕분에 다중 플랫폼 이미지를 빌드하고 캐시를 내보내는 데 사용됩니다.
        # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

        # "GitHub Action"을 사용하여 Docker 레지스트리에 로그인합니다.
        # https://github.com/docker/login-action
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

        # https://github.com/docker/build-push-action
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.dev
          push: true
          tags: coolwu/mbti-channel:dev-latest
