name: node.js CI
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  job-install-dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["14", "16"] # 테스트할 노드 환경
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # node module 캐싱
      - name: Cache node modules
        uses: actions/cache@v3
        id: cache-npm
        with:
          path: ~/.npm # npm 캐시 파일 경로
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }} # 캐시를 저장할때 생성되는 키
          # key로 못찾았다면 찾는 대체키
          restore-keys: |
            ${{ runner.os }}-node-modules-
      # 라이브러리 설치. 일치하는 키가 없다면 설치
      - name: Install Dependencies
        if: steps.cache-npm.outputs.cache-hit == 'false'
        run: npm install

      # 테스트 실행
      - run: npm test
        #env:
        #KEY: ${{ secrets.KEY}}
