name: "test-pr"
on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  project-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["16"]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Cache npm dependency
        uses: actions/cache@v3
        id: npm-cache
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # 캐시가 없다면 npm ci
      - name: Install Dependency
        if: steps.npm-cache.outputs.cache-hit != true
        run: |
          echo 'npm cache missed'
          npm ci

      # 테스트 실행
      - name: Run Test
        run: npm test
        #env:
        #KEY: ${{ secrets.KEY}}
